// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imvipnxumgkhcsrgimpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltdmlwbnh1bWdraGNzcmdpbXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTA2NTgsImV4cCI6MjA1NTg2NjY1OH0.w5rQojT5BskHxH3QtLneOsJjME4RwibC0Gk6wXwzwGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);